version: "3.8"
   
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=ident
      - POSTGRES_DB=RYM
  app:
    build: ./app
    environment:
      - DB_HOST=db
    command: sh -c "python3 main.py && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db